---
title: "extra notes"
author: "Stephen Franklin"
date: "May 27, 2015"
output: html_document
---

****

Animal feed is separated into two main components: 20% concentrates and 80% roughages. Concentrates are feeds which contain high levels of nutrients and less than 18% crude fiber content. Concentrates include cereals, roots and tubers, oil crops, oil meals, bran, molasses, pulses, sugar crops, fruits and vegetables. Roughages are feeds with over 18% crude fiber content and low nutrient density. Roughages include forage cereals such as corn, oats, sorghum; oilseeds such as winter rape; roots and tubers such as potatoes, beets, swedes, and turnips; pulses such as field peas, beans, sweet lupins, and vetches; pumpkins; cabbages; sugarcane; lucerne (alfalfa); berseem; pastures; and straw and chaff from cereals and pulses. Other synonyms for animal feed are fodder, forage, hay, haylage, greenchop, etc.

The UNESCO_IHE reports list water footprints (in $m^3/ton$) and ratios of the many ingredients of animal feed products by nation. But strangely, the water footprint for alfalfa, which represents a large portion of animal feed grown in California, isn't provided. The ratio of ingredients in animal feed widely varies by nation as well as by animal. The USDA Field Crops Report for California lists the production weight by year for several categories that may constitute animal feed including "Forage, Alfalfa", "Hay, Alfalfa", "Haylage And Greenchop", "Corn For Silage", and "Sorghum For Silage". Pacific Intstitute's report (Figure 4) shows California's overall water footprints (in acre-feet per year). 

##### Table 8: Animal Feed Crops in California in 2013

Crop                | Weight (short tons)   | notes
--------------------|-----------------------|-------
corn for silage     |  10,998,000           |
forage, all         |   9,362,000           | incl. alfalfa forage
hay, all            |   7,646,000           | incl. alfalfa hay
haylage & greenchop |   3,472,000           |
sorghum for silage  |     646,000           | 2008
total               |  32,124,000           |

http://www.nass.usda.gov/Statistics_by_State/California/Publications/California_Ag_Statistics/CAFieldCrops.pdf


U.S. beef 2013 (billion lb): 
consumption: 25.5; production: 25.7; exported: 2.6
imported: 2.4;
http://www.ers.usda.gov/topics/animal-products/cattle-beef/statistics-information.aspx

beef yield is 45% of live weight. http://www.cattletoday.com/forum/viewtopic.php?f=8&t=43995

cows slaughtered in 2013: 32.459 million
25.7*10^9 lbs of beef / 32*10^6 cows = 800 lbs per cow. at 1660 per cow and a 50% meat yield that is a perfectly reasonable number of slaugtered cows.
http://www.humanesociety.org/news/resources/research/stats_slaughter_totals.html

25.5 billion lbs = 1,275,000 short tons.

25.7 billion lbs * 14191 m^3/metric ton = 165.4 billion cubic meters
= 134.1 million acre feet

California is 12% of the US population.
consumption: .12 * 25.5 = 3.06 billion lbs = 1,530,000 short tons
1.5 million short tons * 14191 m^3/metric ton = 19.31 billion cubic meters
= 15.65 million acre feet.

2013
89 million cattle in US. 24.3 * 10^8 / 88 * 10^6 = 276 lbs
should be more like 4-500. so maybe half the cattle were used for dairy.
Cattle and calves on feed for slaughter in all feedlots, 12.7 million:
at 50% carcass meat, 12.7*10^6 * 1660 lbs/2 =~ 10 billion lbs
but there was 25.7 billion lbs produced.


2013 CA
5.3 million cattle and calves. 
CA produced 1 million sh tons of live cattle 2013
5.3 million cattle * 1299/2000  = 3.4 million sh tons 
if all the cattle were of a small breed: 1.6 million tons

1,742,000 cattle slaughtered at a weight of 1299 lb. p4. 
1,742,000 * 1299/2000 = 1,131,429 sh tons
1,131,429 sh tons *0.45 = 509,143 sh tons of beef.
509,143 sh tons * 14191 m^3/metric ton = 6.555 billion cubic meters water
= 5.314 million acre-feet.

176,000 calves at 102 lbs
176,000 * 102/2000 = 8976 sh tons
8976 sh tons *0.45 = 4039 sh tons
4039 sh tons * 14191 m^3/metric ton = 0.52 billion cubic meters water
= 0.042 million acre-feet.


pigs 2,365,000 at 245 lb.
2365000 * 245/2000 * 0.57 = 165,136 sh tons.
165136 sh tons * 5508 m^3 per metric ton = 825 million m^3 = 669,000 acre feet
yield is 57%
http://www.oda.state.ok.us/food/fs-hogweight.pdf

Of the 5.3 million:
beef cows that have calved 610,000  milk cows that have calved 1,780,000
heifers beef cow replacement 110,000 heifers milk cow replacement 780,000
heifers other 220,000
steers 620,000   bulls 70,000   calves (under 500 lbs) 1,110,000

CA total cattle on feed i.e. to be meat 510,000
http://usda.mannlib.cornell.edu/usda/nass/Catt//2010s/2014/Catt-01-31-2014.pdf
510,000 * 1660 lbs /2 = 423 million lbs of beef
423*10^6 lbs * 14191 m^3/metric ton = 2.723 billion m^3 = 2.2 million acre feet



US
Year  Cattle Cows Beef-Production 
(000) (000) (mil lbs.) (lbs.) 
1980 111,242 47,866 21,469 449 
2009 94,521 41,045 25,951 632 



Top California Commodities in 2013

Commodity           | Weight (short tons)   | Value (US$)     | rank
--------------------|-----------------------|---------------|-------
Milk and Cream      | 20,630,000            | 7,617,641,000 | 1
Almonds (shelled)   |  1,005,000            | 5,768,100,000 | 2
Grapes              |  7,717,000            | 5,585,584,000 | 3
Cattle & Calves     |  1,020,000            | 3,048,390,000 | 4
Strawberries        |  1,378,000            | 2,200,729,000 | 5
Walnuts             |    492,000            | 1,795,800,000 | 6
Lettuce             |  2,987,700            | 1,679,164,000 | 7
Hay, Alfalfa, etc   |  7,956,000            | 1,569,780,000 | 8
Tomatoes            | 12,520,000            | 1,222,470,000 | 9
Nursery             | NA                    | 1,219,800,000 | 10
corn for grain      |    982,800            |   194,805,000 | 32
beans, dry          |     57,500            |    61,410,000 | 49

http://www.nass.usda.gov/Statistics_by_State/California/Publications/California_Ag_Statistics/CA_Ag_Overview.pdf


California’s dairies produced 41.3 billion pounds of milk, accounting for almost 21 percent of the nation's milk supply.  (usda p1)
cream 1484 ;  185,664,000 +  127,508,000 +  27,940,000 = 341112000 lb =170556
milk 822 ;    593,910,000 +  583,106,000 + 54,601,000 = 1231617000 lb =615809

822 (m^3/metric ton) * 20.6*10^6 short tons = 12.5 million acre feet = 15.4 km^3
1484 (m^3/metric ton) * 20.6*10^6 short tons = 22.5 million acre feet = 27.7 km^3

*****

http://www.nass.usda.gov/Statistics_by_State/California/Publications/California_Ag_Statistics/CALivestockandDairy.pdf
dairy p7
cheese 2,313,000,000 lbs
yogurt 620,171,000 lbs in 2009
milk 41.3 billion lbs  44.2% went to cheese (dairy 2013: $7,617,641,000)
cream 185,664,000 + 127,508,000
eggs 5.05 billion
cattle and calves live 2,039,468,000 lbs    $3,059,175,000
sheep and lambs live 45,791,000 lbs         $   67,182,000 2010
hogs and pigs live 47,708,000 lbs           $   41,556,000
turkey meat 365,300,000 lbs                 $  242,925,000

turkey 165697 metric tons * 2218 m^3/ metric ton = 367.5 million m^3 of water
= 297936 acre feet.

if all the cattle were used for beef that would be
beef 
14141 m3/m.ton * 2039468000 lbs = 13.08 billion m3 = 10.6 million acre feet. 

hay, alfalfa: 
15.2 million acre feet / 7,956,000 short tons = 2.598 m3/kg = 2598 m3/ton = 259.8 L/100g
That seems reasonable; it's close to what rice is.


meat animals 2013 $3,088,751,000


****
2013: top CA commodities
Milk and Cream  $7,617,641,000  almost 21 percent of the nation's milk supply. Asian markets imported 53 percent of US dairy exports in 2013
Almonds         $5,768,100,000    99% of the nation
Grapes          $5,585,584,000    leads the nation
Cattle & Calves $3,048,390,000    
meat animal     $3,088,751,000


http://www.nass.usda.gov/Statistics_by_State/California/Publications/California_Ag_Statistics/CA_Ag_Overview.pdf

****
general source for CA 2013 yields: 
http://www.nass.usda.gov/Statistics_by_State/California/Publications/California_Ag_Statistics/index.asp

******

harvested roughages: include those which are sown and harvested annually for forage, fodder or silage. The principal types of
harvest roughages include forage (green) cereals such as maize, oats and sweet sorghum; sugarcane, lucerne (alfalfa) and berseem
(Egyptian clover); special high yielding grasses cultivated chiefly for silage (such as Thimoth grass); roots and tubers such as
potatoes, beets, swedes, turnips; oilseeds such as winter rape; pulses such as field peas, beans, sweet lupins and vetches;
vegetables such as pumpkins and cabbages. These feeds are sometimes processed for lower fibre content and bulk and are then
usually classified as concentrate feeds (e.g. cassava chips and pellets, processed alfalfa, pea and bean meals).  (p14)

The total feed consumption
over the period 1996-2005 was 4996 million ton feed in dry matter per year, on average. Roughages account for
the largest share out of this total, accounting for 80%, and feeds derived from crop production account for the
remaining 20%.  (p20)

http://waterfootprint.org/media/downloads/Report-48-WaterFootprint-AnimalProducts-Vol1.pdf

*****

#### Conversions:
#### 1000 cubic meters / metric ton
#### = 120 gallons / pound
#### = 26.4 gallons / 100 grams  
#### ~or~ 4000 m3/t = 100 gal / 100 g

## 1/2 lb hamburger: 14000 m3/t = 14*120/2 = 840 gallons
## 1/2 lb almonds:   13000 m3/t = 13*120/2 = 780 gallons

These lines are _going to_ intersect<sup>1</sup>!

...

--------

**Footnotes:**

1. See Euclid's 5<sup>th</sup> postulate.
